const path = require('path'); process.argv[2] = path.join(__dirname, '../../backend/Code.gs');
const m = require('./mock.js'); const logs = []; const ol = console.log; console.log = (...a) => logs.push(a.join(' ')); m.ctx.setup(); console.log = ol;
const pin = (logs.join('\n').match(/PIN[^0-9]*(\d{4})/) || [])[1]; const A = m.call('login', { name: 'แอดมิน', pin }).data.token;
const mk = n => { const r = m.call('saveUser', { user: { name: n, role: 'user' } }, A).data; return m.call('login', { userId: r.user.id, pin: r.pin }).data.token; };
const T1 = mk('หมี'), T2 = mk('อีฟ');
m.call('saveJob', { job: { code: 'F-1', status: 'queue', assignee: 'หมี', sale: 'ป้อม', checklist: JSON.stringify([{ t: 'เช็กขนาด', d: 1 }, { t: 'ส่ง sale', d: 0 }]) } }, A);
const id = m.call('bootstrap', {}, A).data.jobs.find(x => x.code === 'F-1').id;
const f = m.call('addFile', { jobId: id, name: 'panel.dwg', mime: 'application/acad', data: 'data:application/acad;base64,' + Buffer.from('DWGDATA').toString('base64') }, T1);
console.log('addFile', f.ok, f.data && f.data.file.name, f.data && !!f.data.file.fileId);
console.log('outsider addFile →', m.call('addFile', { jobId: id, name: 'x.nc', data: 'QUJD' }, T2).error);
const b = m.call('bootstrap', {}, T1).data; console.log('bootstrap files', b.files.length, '| checklist kept', b.jobs.find(x => x.id === id).checklist);
const c = m.call('addComment', { jobId: id, text: 'ขนาดผิด ช่วยแก้ด้วย' }, T2); console.log('comment by non-member', c.ok);
console.log('comments', m.call('comments', { jobId: id }, T1).data.comments.length, '| counts', JSON.stringify(m.call('bootstrap', {}, A).data.cmtCount));
console.log('delete others comment →', m.call('deleteComment', { id: c.data.comment.id }, T1).error);
console.log('saleView no key →', m.call('saleView', { k: 'x' }).error);
const key = m.call('saleLink', {}, A).data.key; const sv = m.call('saleView', { k: key, sale: 'ป้อม' });
console.log('saleView', sv.ok, sv.data.jobs.length, JSON.stringify(sv.data.jobs[0]));
console.log('user saleLink →', m.call('saleLink', {}, T1).error);
console.log('delete file', m.call('deleteFile', { id: f.data.file.id }, T1).ok, m.call('bootstrap', {}, A).data.files.length);
m.call('addFile', { jobId: id, name: 'b.nc', data: 'QUJD' }, T1);
console.log('deleteJob cleans', m.call('deleteJob', { id }, A).ok, m.call('bootstrap', {}, A).data.files.length, JSON.stringify(m.call('bootstrap', {}, A).data.cmtCount));
