const { chromium } = await import(process.env.PW);
import http from 'http'; import fs from 'fs'; import path from 'path';
const root = new URL('..', import.meta.url).pathname;
const srv = http.createServer((q, r) => { let p = path.join(root, q.url.split('?')[0]); if (p.endsWith('/')) p += 'index.html'; if (!fs.existsSync(p)) { r.writeHead(404); return r.end(); } let b = fs.readFileSync(p); if (p.endsWith('config.js')) b = 'window.KIWNGAN_CONFIG={}'; if (p.endsWith('app.js')) b = b.toString().replace('window.KiwNgan = {', 'window.T={moveJob,uploadImages,imgsOf,jobAlerts,go};window.S=S;window.KiwNgan = {'); r.writeHead(200, { 'content-type': { '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html' }[path.extname(p)] || 'application/octet-stream' }); r.end(b); }).listen(8773);
const b = await chromium.launch({ args: ['--no-proxy-server'] }); const pg = await b.newPage({ viewport: { width: 1300, height: 850 } });
const errs = []; pg.on('pageerror', e => errs.push(e.message));
await pg.addInitScript(() => { localStorage.clear(); if (navigator.serviceWorker) navigator.serviceWorker.register = () => Promise.resolve(); });
await pg.goto('http://127.0.0.1:8773/index.html'); await pg.waitForTimeout(600);
await pg.click('[data-act="adminon"]'); await pg.fill('#adminName', 'แอดมิน'); await pg.fill('#pinIn', '1234'); await pg.dispatchEvent('#pinIn', 'input'); await pg.press('#pinIn', 'Enter'); await pg.waitForTimeout(1200);
console.log('due notice shown at login', await pg.locator('.ntf.job-due').count());
await pg.evaluate(() => T.go('board')); await pg.waitForTimeout(500);
const id = await pg.evaluate(async () => { const j = S.jobs.find(x => x.status === 'doing' && !/CAM/.test(x.taskType) && !S.jobs.some(y => y !== x && y.code === x.code)); const c = document.createElement('canvas'); c.width = 50; c.height = 50; const blob = await new Promise(r => c.toBlob(r, 'image/png')); await T.uploadImages(j.id, [new File([blob], 'a.png', { type: 'image/png' })]); await T.moveJob(j.id, 'done'); return j.id; });
await pg.waitForTimeout(500);
console.log('ask shown', await pg.locator('#askBox.show').count(), await pg.locator('#askBox b').textContent());
await pg.screenshot({ path: new URL('out/cam-ask.png', import.meta.url).pathname });
await pg.click('#askBox [data-camyes]'); await pg.waitForTimeout(1200);
console.log('cam job', JSON.stringify(await pg.evaluate(id => { const s = S.jobs.find(j => j.id === id); const c = S.jobs.find(j => j.code === s.code && /CAM/.test(j.taskType)); return c && { type: c.taskType, status: c.status, title: c.title === s.title, imgs: T.imgsOf(c.id).length, pending: !!c.pending }; }, id)));
// assign notification simulation
const n0 = await pg.locator('.ntf.job-assign').count();
await pg.evaluate(() => { const prev = JSON.parse(JSON.stringify(S.jobs)); const j = S.jobs.find(x => x.assignee !== S.me && x.status !== 'done'); j.assignee = S.me; j.updatedBy = 'ต้น'; T.jobAlerts(prev); });
await pg.waitForTimeout(300);
console.log('assign notice', (await pg.locator('.ntf.job-assign').count()) - n0);
console.log('errors', errs.join(' | ') || 'none');
await b.close(); srv.close();
