const { chromium } = await import(process.env.PW);
import http from 'http'; import fs from 'fs'; import path from 'path';
const root = new URL('..', import.meta.url).pathname;
const srv = http.createServer((q, r) => { let p = path.join(root, q.url.split('?')[0]); if (p.endsWith('/')) p += 'index.html'; if (!fs.existsSync(p)) { r.writeHead(404); return r.end(); } let b = fs.readFileSync(p); if (p.endsWith('config.js')) b = 'window.KIWNGAN_CONFIG={}'; if (p.endsWith('app.js')) b = b.toString().replace('window.KiwNgan = {', 'window.T={moveJob,uploadImages,imgsOf,jobAlerts,go};window.S=S;window.KiwNgan = {'); r.writeHead(200, { 'content-type': { '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html' }[path.extname(p)] || 'application/octet-stream' }); r.end(b); }).listen(8778);
const b = await chromium.launch({ args: ['--no-proxy-server'] }); const pg = await b.newPage({ viewport: { width: 1300, height: 850 } });
const errs = []; pg.on('pageerror', e => errs.push(e.message));
await pg.addInitScript(() => { localStorage.clear(); if (navigator.serviceWorker) navigator.serviceWorker.register = () => Promise.resolve(); });
await pg.goto('http://127.0.0.1:8778/index.html'); await pg.waitForTimeout(600);
await pg.click('[data-act="adminon"]'); await pg.fill('#adminName', 'แอดมิน'); await pg.fill('#pinIn', '1234'); await pg.dispatchEvent('#pinIn', 'input'); await pg.press('#pinIn', 'Enter'); await pg.waitForTimeout(1200);
console.log('due notice shown at login', await pg.locator('.ntf.job-due').count());
await pg.evaluate(() => document.querySelectorAll('.ntf').forEach(e => e.remove()));
await pg.evaluate(() => { ['หมี','มิ้ม','อีฟ','พิชัย','แจ็ค'].forEach((n, i) => S.users.push({ id: 'x' + i, name: n, role: 'user', active: true, color: '#888' })); });
await pg.click('[data-act="msgopen"]'); await pg.waitForTimeout(600);
const r = await pg.evaluate(() => { const c = document.querySelector('.mp-chans'); const chips = [...c.querySelectorAll('.mp-ch')]; const cr = c.getBoundingClientRect(); return { n: chips.length, allVisible: chips.every(b => { const x = b.getBoundingClientRect(); return x.right <= cr.right + 1 && x.left >= cr.left - 1; }), w: document.querySelector('#msgPanel').offsetWidth }; });
console.log(JSON.stringify(r));
await pg.locator('#msgPanel').screenshot({ path: new URL('out/chat.png', import.meta.url).pathname });
console.log('errors', errs.join(' | ') || 'none');
await b.close(); srv.close();
