const { chromium } = await import(process.env.PW);
import http from 'http'; import fs from 'fs'; import path from 'path';
const root = new URL('..', import.meta.url).pathname;
const srv = http.createServer((q, r) => { let p = path.join(root, q.url.split('?')[0]); if (p.endsWith('/')) p += 'index.html'; if (!fs.existsSync(p)) { r.writeHead(404); return r.end(); } let b = fs.readFileSync(p); if (p.endsWith('config.js')) b = 'window.KIWNGAN_CONFIG={}'; if (p.endsWith('app.js')) b = b.toString().replace('window.KiwNgan = {', 'window.T={moveJob,uploadImages,imgsOf,jobAlerts,go};window.S=S;window.KiwNgan = {'); r.writeHead(200, { 'content-type': { '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html' }[path.extname(p)] || 'application/octet-stream' }); r.end(b); }).listen(8775);
const b = await chromium.launch({ args: ['--no-proxy-server'] }); const pg = await b.newPage({ viewport: { width: 1300, height: 850 } });
const errs = []; pg.on('pageerror', e => errs.push(e.message));
await pg.addInitScript(() => { localStorage.clear(); if (navigator.serviceWorker) navigator.serviceWorker.register = () => Promise.resolve(); });
await pg.goto('http://127.0.0.1:8775/index.html'); await pg.waitForTimeout(600);
await pg.click('[data-act="adminon"]'); await pg.fill('#adminName', 'แอดมิน'); await pg.fill('#pinIn', '1234'); await pg.dispatchEvent('#pinIn', 'input'); await pg.press('#pinIn', 'Enter'); await pg.waitForTimeout(1200);
console.log('due notice shown at login', await pg.locator('.ntf.job-due').count());
await pg.evaluate(() => T.go('home')); await pg.waitForTimeout(700);
await pg.evaluate(() => { const c = document.querySelector('[data-act=ganttdone]'); c.checked = true; c.dispatchEvent(new Event('change', { bubbles: true })); }); await pg.waitForTimeout(300);
const info = await pg.evaluate(() => ({ rows: document.querySelectorAll('.gantt .grow').length, chips: [...document.querySelectorAll('.gantt-chips .hp-chip')].map(b => b.textContent.trim()), bars: document.querySelectorAll('.gact').length, late: document.querySelectorAll('.glate').length, done: document.querySelectorAll('.gdone').length }));
console.log(JSON.stringify(info));
const el = pg.locator('.gantt-p'); await el.scrollIntoViewIfNeeded(); await el.screenshot({ path: new URL('out/gantt.png', import.meta.url).pathname });
await pg.locator('.gantt-chips .hp-chip').nth(1).click(); await pg.waitForTimeout(300);
console.log('filtered rows', await pg.locator('.gantt .grow').count());
await pg.locator('.gantt .grow').first().click(); await pg.waitForTimeout(400);
console.log('editor opened', await pg.evaluate(() => !!S.edit));
await pg.setViewportSize({ width: 390, height: 800 }); await pg.click('[data-act="close"]').catch(() => {}); await pg.evaluate(() => T.go('home')); await pg.waitForTimeout(500);
await pg.locator('.gantt-p').screenshot({ path: new URL('out/gantt-m.png', import.meta.url).pathname });
console.log('page h-scroll', await pg.evaluate(() => document.documentElement.scrollWidth > innerWidth));
console.log('errors', errs.join(' | ') || 'none');
await b.close(); srv.close();
