const { chromium } = await import(process.env.PW);
import http from 'http'; import fs from 'fs'; import path from 'path';
const root = new URL('..', import.meta.url).pathname;
const srv = http.createServer((q, r) => { let p = path.join(root, q.url.split('?')[0]); if (p.endsWith('/')) p += 'index.html'; if (!fs.existsSync(p)) { r.writeHead(404); return r.end(); } let b = fs.readFileSync(p); if (p.endsWith('config.js')) b = 'window.KIWNGAN_CONFIG={}'; if (p.endsWith('app.js')) b = b.toString().replace('window.KiwNgan = {', 'window.T={moveJob,uploadImages,imgsOf,jobAlerts,go};window.S=S;window.KiwNgan = {'); r.writeHead(200, { 'content-type': { '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html' }[path.extname(p)] || 'application/octet-stream' }); r.end(b); }).listen(8779);
const b = await chromium.launch({ args: ['--no-proxy-server'] }); const pg = await b.newPage({ viewport: { width: 1300, height: 850 } });
const errs = []; pg.on('pageerror', e => errs.push(e.message));
await pg.addInitScript(() => { localStorage.clear(); if (navigator.serviceWorker) navigator.serviceWorker.register = () => Promise.resolve(); });
await pg.goto('http://127.0.0.1:8779/index.html'); await pg.waitForTimeout(600);
await pg.click('[data-act="adminon"]'); await pg.fill('#adminName', 'แอดมิน'); await pg.fill('#pinIn', '1234'); await pg.dispatchEvent('#pinIn', 'input'); await pg.press('#pinIn', 'Enter'); await pg.waitForTimeout(1200);
console.log('due notice shown at login', await pg.locator('.ntf.job-due').count());
await pg.evaluate(() => { document.querySelectorAll('.ntf').forEach(e => e.remove()); T.go('home'); }); await pg.waitForTimeout(600);
const n0 = await pg.locator('.gantt .grow').count();
await pg.selectOption('[data-grange]', 'month'); await pg.waitForTimeout(400);
console.log('auto rows', n0, '→ month rows', await pg.locator('.gantt .grow').count(), 'inputs', await pg.locator('[data-gfrom]').inputValue(), await pg.locator('[data-gto]').inputValue());
await pg.fill('[data-gfrom]', '2026-09-20'); await pg.dispatchEvent('[data-gfrom]', 'change'); await pg.waitForTimeout(300);
await pg.fill('[data-gto]', '2026-09-30'); await pg.dispatchEvent('[data-gto]', 'change'); await pg.waitForTimeout(300);
const r = await pg.evaluate(() => ({ sel: document.querySelector('[data-grange]').value, rows: document.querySelectorAll('.gantt .grow').length, ticks: [...document.querySelectorAll('.gt')].map(x => x.textContent).join(','), today: !!document.querySelector('.gtoday') }));
console.log(JSON.stringify(r));
await pg.locator('.gantt-p').screenshot({ path: new URL('out/grange.png', import.meta.url).pathname });
await pg.selectOption('[data-grange]', 'auto'); await pg.waitForTimeout(300);
console.log('back to auto', await pg.locator('.gantt .grow').count(), 'checkbox', await pg.locator('[data-act=ganttdone]').count());
console.log('errors', errs.join(' | ') || 'none');
await b.close(); srv.close();
