const { chromium } = await import(process.env.PW);
import http from 'http'; import fs from 'fs'; import path from 'path';
const root = new URL('..', import.meta.url).pathname;
const srv = http.createServer((q, r) => { let p = path.join(root, q.url.split('?')[0]); if (p.endsWith('/')) p += 'index.html'; if (!fs.existsSync(p)) { r.writeHead(404); return r.end(); } let b = fs.readFileSync(p); if (p.endsWith('config.js')) b = 'window.KIWNGAN_CONFIG={}'; if (p.endsWith('app.js')) b = b.toString().replace('window.KiwNgan = {', 'window.T={moveJob,uploadImages,imgsOf,jobAlerts,go,openEditor};window.S=S;window.KiwNgan = {'); r.writeHead(200, { 'content-type': { '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html' }[path.extname(p)] || 'application/octet-stream' }); r.end(b); }).listen(8781);
const b = await chromium.launch({ args: ['--no-proxy-server'] }); const pg = await b.newPage({ viewport: { width: 1300, height: 850 } });
const errs = []; pg.on('pageerror', e => errs.push(e.message));
await pg.addInitScript(() => { if (!sessionStorage.getItem('kn-init')) { localStorage.clear(); sessionStorage.setItem('kn-init', '1'); } if (navigator.serviceWorker) navigator.serviceWorker.register = () => Promise.resolve(); });
await pg.goto('http://127.0.0.1:8781/index.html'); await pg.waitForTimeout(600);
await pg.click('[data-act="adminon"]'); await pg.fill('#adminName', 'แอดมิน'); await pg.fill('#pinIn', '1234'); await pg.dispatchEvent('#pinIn', 'input'); await pg.press('#pinIn', 'Enter'); await pg.waitForTimeout(1200);
console.log('due notice shown at login', await pg.locator('.ntf.job-due').count());
await pg.evaluate(() => { document.querySelectorAll('.ntf').forEach(e => e.remove()); T.go('board'); }); await pg.waitForTimeout(500);
console.log('cards with team avatars', await pg.locator('.card .av-team').count());
const id = await pg.evaluate(() => S.jobs.find(j => j.status === 'queue' && !j.helpers).id);
await pg.evaluate(id => T.openEditor(id), id); await pg.waitForTimeout(500); await pg.click('[data-act="editmode"]'); await pg.waitForTimeout(300);
console.log('dbg', await pg.evaluate(() => [!!S.edit, !!document.querySelector('.helper-pick'), (document.querySelector('#sheetBody')||{}).innerText?.slice(0,200)]));
const btns = pg.locator('.helper-pick .hp-mem'); console.log('picker members', await btns.count());
await btns.nth(0).click(); await pg.waitForTimeout(150); await btns.nth(1).click(); await pg.waitForTimeout(150);
console.log('selected', await pg.locator('.hp-mem.on').count());
await pg.locator('#sheetBody').screenshot({ path: new URL('out/helpers-ed.png', import.meta.url).pathname }).catch(() => {});
await pg.click('[data-act="save"]'); await pg.waitForTimeout(2500); console.log('db helpers', await pg.evaluate(id => (JSON.parse(localStorage.getItem('kiwngan:demo')).jobs.find(j => j.id === id) || {}).helpers, id));
const h = await pg.evaluate(id => S.jobs.find(j => j.id === id).helpers, id); console.log('saved helpers', h);
// log in as a helper (staff) and check visibility + timer permission
const name = h.split(',')[0];
await pg.evaluate(() => { localStorage.removeItem('kiwngan:demo:token'); });
await pg.evaluate(() => Object.keys(localStorage).filter(k => /token/.test(k)).forEach(k => localStorage.removeItem(k)));
await pg.reload(); await pg.waitForTimeout(800);
await pg.click('.who:has-text("' + name + '")'); await pg.fill('#pinIn', '1234'); await pg.dispatchEvent('#pinIn', 'input'); await pg.press('#pinIn', 'Enter'); await pg.waitForTimeout(1200);
console.log('dbg2', await pg.evaluate(id => { const j = S.jobs.find(x => x.id === id); return [S.jobs.length, j && j.helpers, j && j.status, S.f.member, S.f.status, S.view]; }, id));
console.log('logged in as', await pg.evaluate(() => S.me), '| sees job in list pool', await pg.evaluate(id => { T.go('list'); return !!document.querySelector('.row[data-open="' + id + '"]'); }, id));
console.log('can edit (helper)', await pg.evaluate(id => { const j = S.jobs.find(x => x.id === id); return !!document.querySelector('.row[data-open="' + id + '"]') && j && (j.helpers || '').includes(S.me); }, id));
await pg.evaluate(id => T.openEditor(id), id); await pg.waitForTimeout(500);
await pg.click('[data-act="editmode"]').catch(() => {}); await pg.waitForTimeout(300);
console.log('editor read-only?', await pg.locator('#sheetBody .banner:has-text("ดูอย่างเดียว")').count(), '| picker locked', await pg.locator('.hp-mem:disabled').count() > 0);
console.log('errors', errs.join(' | ') || 'none');
await b.close(); srv.close();
