const { chromium } = await import(process.env.PW);
import http from 'http'; import fs from 'fs'; import path from 'path';
const root = new URL('..', import.meta.url).pathname;
const srv = http.createServer((q, r) => { let p = path.join(root, q.url.split('?')[0]); if (p.endsWith('/')) p += 'index.html'; if (!fs.existsSync(p)) { r.writeHead(404); return r.end(); } let b = fs.readFileSync(p); if (p.endsWith('config.js')) b = 'window.KIWNGAN_CONFIG={}'; if (p.endsWith('app.js')) b = b.toString().replace('window.KiwNgan = {', 'window.T={moveJob,uploadImages,imgsOf,jobAlerts,go,openEditor};window.S=S;window.KiwNgan = {'); r.writeHead(200, { 'content-type': { '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html' }[path.extname(p)] || 'application/octet-stream' }); r.end(b); }).listen(8783);
const b = await chromium.launch({ args: ['--no-proxy-server'] }); const pg = await b.newPage({ viewport: { width: 1300, height: 850 } });
const errs = []; pg.on('pageerror', e => errs.push(e.message));
await pg.addInitScript(() => { localStorage.clear(); if (navigator.serviceWorker) navigator.serviceWorker.register = () => Promise.resolve(); });
await pg.goto('http://127.0.0.1:8783/index.html'); await pg.waitForTimeout(600);
await pg.click('[data-act="adminon"]'); await pg.fill('#adminName', 'แอดมิน'); await pg.fill('#pinIn', '1234'); await pg.dispatchEvent('#pinIn', 'input'); await pg.press('#pinIn', 'Enter'); await pg.waitForTimeout(1200);
console.log('due notice shown at login', await pg.locator('.ntf.job-due').count());
await pg.evaluate(() => { document.querySelectorAll('.ntf').forEach(e => e.remove()); S.settings.checklists = { 'ทำ CAD': 'เช็กขนาด\nส่ง sale ตรวจ' }; });
await pg.evaluate(() => T.openEditor()); await pg.waitForTimeout(400);
console.log('sections', await pg.evaluate(() => [...document.querySelectorAll('#sheetBody fieldset.nx legend')].map(l => l.textContent).join(',')));
await pg.fill('#e-code', 'NX-1'); await pg.selectOption('#e-type', 'ทำ CAD'); await pg.waitForTimeout(300);
console.log('due auto', await pg.evaluate(() => S.edit.job.due), '| tpl btn', await pg.locator('[data-act="ncltpl"]').count());
await pg.fill('#eCmt', 'ลูกค้าขอขอบมน');
await pg.click('[data-act="ncltpl"]'); await pg.waitForTimeout(200);
await pg.fill('#nclNew', 'ส่งต่อ CAM'); await pg.press('#nclNew', 'Enter'); await pg.waitForTimeout(200);
await pg.setInputFiles('[data-pfile]', { name: 'A.dxf', mimeType: 'application/dxf', buffer: Buffer.from('0\nSECTION') }); await pg.waitForTimeout(300);
console.log('steps', await pg.locator('fieldset.nx .cl-it').count(), '| pending files', await pg.locator('fieldset.nx .frow').count(), '| cmt kept', await pg.inputValue('#eCmt'));
await pg.locator('#sheetBody').screenshot({ path: new URL('out/newx.png', import.meta.url).pathname });
await pg.click('[data-act="save"]'); await pg.waitForTimeout(2500);
const r = await pg.evaluate(() => { const j = S.jobs.find(x => x.code === 'NX-1'); return { cl: j && j.checklist, files: (S.files || []).filter(f => f.jobId === (j && j.id)).map(f => f.name), cmts: (S.cmtCount || {})[j && j.id] }; });
console.log(JSON.stringify(r));
console.log('errors', errs.join(' | ') || 'none');
await b.close(); srv.close();
