// ฝ่ายผลิตเพิ่มงานที่ไม่ผ่านฝ่ายแบบ: ข้อมูลงาน Sale กำหนดส่ง รูป
const { chromium } = await import(process.env.PW);
import http from 'http'; import fs from 'fs'; import path from 'path';
const root = new URL('..', import.meta.url).pathname, out = new URL('out/', import.meta.url).pathname; fs.mkdirSync(out, { recursive: true });
const srv = http.createServer((q, r) => { let p = path.join(root, q.url.split('?')[0]); if (p.endsWith('/')) p += 'index.html'; if (!fs.existsSync(p)) { r.writeHead(404); return r.end(); } let b = fs.readFileSync(p); if (p.endsWith('config.js')) b = 'window.KIWNGAN_CONFIG={}'; if (p.endsWith('app.js')) b = b.toString().replace('window.KiwNgan = {', 'window.T={go,saveJob,api};window.S=S;window.KiwNgan = {'); r.writeHead(200, { 'content-type': { '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html' }[path.extname(p)] || 'application/octet-stream' }); r.end(b); }).listen(8795);
const b = await chromium.launch({ args: ['--no-proxy-server'] }); const pg = await b.newPage({ viewport: { width: 1400, height: 900 } });
const errs = []; pg.on('pageerror', e => errs.push(e.message));
let ok = 0, bad = 0; const eq = (lbl, a, w) => { const p = JSON.stringify(a) === JSON.stringify(w); p ? ok++ : bad++; console.log((p ? 'ok  ' : 'FAIL') + ' ' + lbl + (p ? '' : ' → got ' + JSON.stringify(a) + ' want ' + JSON.stringify(w))); };
await pg.addInitScript(() => { if (!sessionStorage.getItem('x')) { localStorage.clear(); sessionStorage.setItem('x', 1); } if (navigator.serviceWorker) navigator.serviceWorker.register = () => Promise.resolve(); });
await pg.goto('http://127.0.0.1:8795/index.html'); await pg.waitForTimeout(700);
await pg.click('[data-act="adminon"]'); await pg.fill('#adminName', 'แอดมิน'); await pg.fill('#pinIn', '1234'); await pg.dispatchEvent('#pinIn', 'input'); await pg.press('#pinIn', 'Enter'); await pg.waitForTimeout(1200);
await pg.evaluate(() => { document.querySelectorAll('.ntf').forEach(e => e.remove()); T.go('prod'); }); await pg.waitForTimeout(600);
const PNG = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAIAAABLbSncAAAAEklEQVR42mP8z8BQz0AEYBxVSF+FAP5FDvcfRYWgAAAAAElFTkSuQmCC', 'base64');
await pg.evaluate(() => document.querySelector('[data-pnew], #fab, [data-act="new"]') && 0);
await pg.evaluate(() => { const b = [...document.querySelectorAll('button')].find(x => /เพิ่มงานเข้าผลิต/.test(x.textContent)); b.click(); }); await pg.waitForTimeout(400);
eq('add modal open', await pg.locator('#pModal .pm-add').count(), 1);
await pg.fill('#pAddCode', 'D-777'); await pg.waitForTimeout(100);
eq('new job hint', await pg.locator('#pAddFound.on').count(), 0);
await pg.fill('#pAddTitle', 'ป้ายร้านกาแฟ คุณบี'); await pg.fill('#pAddNote', 'อะคริลิก 5 มม.');
const sale = await pg.evaluate(() => { const o = [...document.querySelectorAll('#pAddSale option')].find(x => x.value); return o && o.value; });
if (sale) await pg.selectOption('#pAddSale', sale);
await pg.click('[data-padue="3"]'); await pg.waitForTimeout(150);
eq('quick due keeps typed title', await pg.inputValue('#pAddTitle'), 'ป้ายร้านกาแฟ คุณบี');
await pg.setInputFiles('#pAddImg', [{ name: 'a.png', mimeType: 'image/png', buffer: PNG }, { name: 'b.png', mimeType: 'image/png', buffer: PNG }]); await pg.waitForTimeout(300);
eq('2 image previews', await pg.locator('#pModal .pa-im img').count(), 2);
await pg.click('[data-padimgdel="1"]'); await pg.waitForTimeout(150);
eq('remove one preview', await pg.locator('#pModal .pa-im img').count(), 1);
await pg.click('[data-paddm="Laser"]'); await pg.waitForTimeout(150);
eq('title kept after machine pick', await pg.inputValue('#pAddTitle'), 'ป้ายร้านกาแฟ คุณบี');
await pg.screenshot({ path: out + 'prod-add.png' });
await pg.click('[data-paddsave]'); await pg.waitForTimeout(2500);
const p = await pg.evaluate(() => { const x = S.prods.find(q => q.code === 'D-777'); return x && { title: x.title, sale: x.sale, due: x.due, stage: x.stage, id: x.id }; });
eq('saved info', p && [p.title, p.sale, !!p.due, p.stage], ['ป้ายร้านกาแฟ คุณบี', sale || '', true, 'machine']);
eq('image uploaded to prod job', await pg.evaluate(id => (S.images || []).filter(m => m.jobId === id).length, p.id), 1);
eq('card shows thumb + due', await pg.evaluate(id => { const c = document.querySelector('.pcard[data-popen="' + id + '"]'); return !!(c && c.querySelector('.card-th') && c.querySelector('.pt-due')); }, p.id), true);
await pg.click('.pcard[data-popen="' + p.id + '"] .title'); await pg.waitForTimeout(500);
eq('detail shows image', await pg.locator('#pModal .pa-imgs .pa-im').count(), 1);
await pg.locator('#pModal .pa-imgs .pa-im').first().click(); await pg.waitForTimeout(500);
eq('lightbox has zoom bar', await pg.locator('#lightbox.open .zm-bar').count(), 1);
await pg.click('#lightbox [data-zm="+"]'); await pg.waitForTimeout(250);
eq('lightbox zooms', await pg.locator('#lightbox .zm-pct').textContent(), '150%');
await pg.keyboard.press('Escape'); await pg.evaluate(() => { const b = document.querySelector('#lightbox [data-lb="close"]'); b && b.click(); }); await pg.waitForTimeout(300);
await pg.click('[data-pinfo="edit"]'); await pg.waitForTimeout(200);
await pg.fill('#pEdTitle', 'ป้ายร้านกาแฟ (แก้)'); await pg.click('[data-pinfo="save"]'); await pg.waitForTimeout(1200);
eq('edited title', await pg.evaluate(id => S.prods.find(q => q.id === id).title, p.id), 'ป้ายร้านกาแฟ (แก้)');
await pg.screenshot({ path: out + 'prod-detail.png' });
// ภาพรวมบริษัท: แถวงานที่ฝ่ายผลิตบันทึกเอง โชว์โน้ต + ชี้แล้วขึ้นการ์ดรายละเอียด
await pg.evaluate(id => T.api && 0, p.id);
await pg.evaluate(async id => { const x = S.prods.find(q => q.id === id); }, p.id);
if (await pg.locator('#pModal [data-pclose]').count()) await pg.locator('#pModal .pm-f [data-pclose]').click(); await pg.waitForTimeout(200); await pg.evaluate(() => T.go('flow')); await pg.waitForTimeout(900);
const prow = pg.locator('.co-row[data-phov="' + p.id + '"]');
eq('prod-only row has hover', await prow.count(), 1);
eq('row shows production note', await prow.locator('.co-pnote').textContent(), 'อะคริลิก 5 มม.');
await prow.hover(); await pg.waitForTimeout(900);
eq('prod hover shows title', await pg.locator('#hovercard.show .hv-head small').textContent(), 'ป้ายร้านกาแฟ (แก้)');
eq('prod hover shows image', await pg.locator('#hovercard.show .hv-hero img').count(), 1);
eq('prod hover shows source', await pg.locator('#hovercard.show', { hasText: 'ฝ่ายผลิตบันทึกเอง' }).count(), 1);
await pg.screenshot({ path: out + 'prod-hover.png' });
await pg.mouse.move(5, 5); await pg.evaluate(() => T.go('prod')); await pg.waitForTimeout(500);
// บอร์ดผลิต: ชี้การ์ดแล้วขึ้นรายละเอียดแบบบอร์ดงาน + โน้ตโชว์บนการ์ด
await pg.mouse.move(5, 5); await pg.waitForTimeout(400);
eq('note text on prod card', await pg.locator('.pcard[data-popen="' + p.id + '"] .pc-notetx span').textContent(), 'อะคริลิก 5 มม.');
await pg.locator('.pcard[data-popen="' + p.id + '"] .title').hover(); await pg.waitForTimeout(900);
eq('prod board hover card', await pg.locator('#hovercard.show .hv-head b').textContent(), 'D-777');
eq('hover beside card fits', await pg.evaluate(() => { const r = document.querySelector('#hovercard').getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth && r.top >= 0 && r.bottom <= innerHeight + 1; }), true);
await pg.screenshot({ path: out + 'prod-board-hover.png' });
await pg.mouse.move(5, 5); await pg.waitForTimeout(500);
const dp = await pg.evaluate(() => { const x = S.prods.find(q => q.stage !== 'shipped' && S.jobs.some(j => j.code === q.code) && document.querySelector('.pcard[data-popen="' + q.id + '"]')); return x && x.id; });
await pg.locator('.pcard[data-popen="' + dp + '"] .code').hover(); await pg.waitForTimeout(900);
eq('design-sourced card shows design jobs', await pg.locator('#hovercard.show', { hasText: 'งานฝ่ายแบบของเลขนี้' }).count(), 1);
await pg.mouse.move(5, 5); await pg.waitForTimeout(400);
// งานที่มีในฝ่ายแบบ: ดึงข้อมูลมาให้
await pg.keyboard.press('Escape'); await pg.evaluate(() => { const m = document.querySelector('#pModal'); if (m) m.remove(); });
const dcode = await pg.evaluate(() => { const have = {}; S.prods.forEach(x => have[x.code.toLowerCase()] = 1); const j = S.jobs.find(x => x.status === 'done' && x.title && !have[x.code.toLowerCase()]); return j && [j.code, j.title]; });
await pg.evaluate(() => { const b = [...document.querySelectorAll('button')].find(x => /เพิ่มงานเข้าผลิต/.test(x.textContent)); b.click(); }); await pg.waitForTimeout(300);
await pg.fill('#pAddCode', dcode[0]); await pg.waitForTimeout(200);
eq('found design job autofills title', await pg.inputValue('#pAddTitle'), dcode[1]);
eq('found hint on', await pg.locator('#pAddFound.on').count(), 1);
console.log(ok + ' ok, ' + bad + ' failed'); console.log('errors', errs.join(' | ') || 'none');
await b.close(); srv.close(); if (bad || errs.length) process.exit(1);
