const { chromium } = await import(process.env.PW);
import http from 'http'; import fs from 'fs'; import path from 'path';
const root = new URL('..', import.meta.url).pathname;
const srv = http.createServer((q, r) => { let p = path.join(root, q.url.split('?')[0]); if (p.endsWith('/')) p += 'index.html'; if (!fs.existsSync(p)) { r.writeHead(404); return r.end(); } let b = fs.readFileSync(p); if (p.endsWith('config.js')) b = 'window.KIWNGAN_CONFIG={}'; if (p.endsWith('app.js')) b = b.toString().replace('window.KiwNgan = {', 'window.T={openEditor,openMsgPanel,go};window.S=S;window.M=M;window.KiwNgan = {'); r.writeHead(200, { 'content-type': { '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html' }[path.extname(p)] || 'application/octet-stream' }); r.end(b); }).listen(8772);
const b = await chromium.launch({ args: ['--no-proxy-server'] }); const pg = await b.newPage({ viewport: { width: 1400, height: 900 } });
const errs = []; pg.on('pageerror', e => errs.push(e.message));
await pg.addInitScript(() => { if (navigator.serviceWorker) navigator.serviceWorker.register = () => Promise.resolve(); });
await pg.goto('http://127.0.0.1:8772/index.html'); await pg.waitForTimeout(600);
await pg.click('[data-act="adminon"]'); await pg.fill('#adminName', 'แอดมิน'); await pg.fill('#pinIn', '1234'); await pg.dispatchEvent('#pinIn', 'input'); await pg.press('#pinIn', 'Enter'); await pg.waitForTimeout(1000);
const j = await pg.evaluate(() => { const j = S.jobs.find(x => x.title && !/CAM/.test(x.taskType) && !S.jobs.some(y => y !== x && y.code === x.code)); return { code: j.code, title: j.title, group: j.group }; });
await pg.evaluate(() => T.openEditor()); await pg.waitForTimeout(400);
await pg.click('#e-title'); await pg.keyboard.type(j.title.slice(0, 1)); await pg.waitForTimeout(200);
console.log('title suggestions', await pg.locator('#suggBox .sugg-it').count(), await pg.locator('#suggBox').isVisible());
await pg.screenshot({ path: new URL('out/sugg-title.png', import.meta.url).pathname });
await pg.locator('#suggBox .sugg-it').first().click(); await pg.waitForTimeout(150);
console.log('title after pick', JSON.stringify(await pg.inputValue('#e-title')));
await pg.fill('#e-code', ''); await pg.click('#e-code'); await pg.keyboard.type(j.code.slice(0, -1)); await pg.waitForTimeout(200);
console.log('code sugg', await pg.evaluate(() => Array.from(document.querySelectorAll('#suggBox .sugg-it')).slice(0, 2).map(x => x.textContent).join(' | ')));
await pg.evaluate(c => { const i = Array.from(document.querySelectorAll('#suggBox .sugg-it')).findIndex(x => x.querySelector('span').textContent === c); document.querySelectorAll('#suggBox .sugg-it')[i].dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true })); }, j.code);
await pg.waitForTimeout(300);
console.log('after code pick', JSON.stringify(await pg.evaluate(() => ({ code: document.querySelector('#e-code').value, title: document.querySelector('#e-title').value, group: document.querySelector('#e-group').value, type: document.querySelector('#e-type').value }))), 'expected', j.title, j.group);
await pg.evaluate(() => document.querySelector('[data-act="close"]').click());
// chat history + keyboard
await pg.evaluate(() => T.openMsgPanel('team')); await pg.waitForTimeout(400);
await pg.fill('#msgText', 'ส่งไฟล์ CAM ให้แล้วครับ'); await pg.press('#msgText', 'Enter'); await pg.waitForTimeout(400);
await pg.click('#msgText'); await pg.keyboard.type('ส'); await pg.waitForTimeout(200);
console.log('msg sugg', await pg.evaluate(() => Array.from(document.querySelectorAll('#suggBox .sugg-it')).map(x => x.textContent).join(' | ')));
const n0 = await pg.evaluate(() => M.list.length);
await pg.keyboard.press('ArrowDown'); await pg.keyboard.press('Enter'); await pg.waitForTimeout(200);
console.log('after Enter on suggestion: text=', JSON.stringify(await pg.inputValue('#msgText')), 'sent?', (await pg.evaluate(() => M.list.length)) !== n0);
await pg.keyboard.press('Enter'); await pg.waitForTimeout(300);
console.log('second Enter sends', (await pg.evaluate(() => M.list.length)) === n0 + 1);
console.log('errors', errs.join('|') || 'none');
await b.close(); srv.close();
