const { chromium } = await import(process.env.PW);
import { createRequire } from 'module'; const require = createRequire(import.meta.url);
const http = require('http'), fs = require('fs'), path = require('path');
process.argv[2] = new URL('../backend/Code.gs', import.meta.url).pathname;
const ol = console.log; const logs = []; console.log = (...a) => logs.push(a.join(' ')); const m = require('./gs/mock.js'); m.ctx.setup(); console.log = ol;
const pin = (logs.join('\n').match(/PIN[^0-9]*(\d{4})/) || [])[1];
const T0 = m.call('login', { name: 'แอดมิน', pin }).data.token;
['A-1', 'A-2', 'A-3'].forEach(c => m.call('saveJob', { job: { code: c, status: 'queue', assignee: 'แอดมิน' } }, T0));
const root = new URL('..', import.meta.url).pathname;
const srv = http.createServer((q, r) => { let p = path.join(root, q.url.split('?')[0]); if (p.endsWith('/')) p += 'index.html'; if (!fs.existsSync(p)) { r.writeHead(404); return r.end(); } let b = fs.readFileSync(p); if (p.endsWith('config.js')) b = "window.KIWNGAN_CONFIG={api:'https://script.google.com/macros/s/T/exec'}"; if (p.endsWith('app.js')) b = b.toString().replace('window.KiwNgan = {', 'window.T={go,openEditor};window.S=S;window.KiwNgan = {'); r.writeHead(200, { 'content-type': { '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html' }[path.extname(p)] || 'application/octet-stream' }); r.end(b); }).listen(8768);
const b = await chromium.launch({ args: ['--no-proxy-server'] }); const pg = await b.newPage({ viewport: { width: 1400, height: 900 } });
const errs = []; pg.on('pageerror', e => errs.push(e.message));
await pg.route('https://script.google.com/**', async route => { const body = route.request().postData() || '{}'; await new Promise(r => setTimeout(r, 1500)); await route.fulfill({ status: 200, contentType: 'application/json', headers: { 'access-control-allow-origin': '*' }, body: m.ctx.doPost({ postData: { contents: body } }).t }); });
await pg.addInitScript(() => { if (navigator.serviceWorker) navigator.serviceWorker.register = () => Promise.resolve(); });
await pg.goto('http://127.0.0.1:8768/index.html'); await pg.waitForTimeout(4000);
await pg.click('[data-act="adminon"]'); await pg.fill('#adminName', 'แอดมิน'); await pg.fill('#pinIn', pin); await pg.dispatchEvent('#pinIn', 'input'); await pg.press('#pinIn', 'Enter'); await pg.waitForTimeout(6000);
await pg.evaluate(() => T.go('board')); await pg.waitForTimeout(800);
const ids = await pg.evaluate(() => S.jobs.map(j => j.id));
let t = Date.now(); await pg.click(`.card[data-id="${ids[0]}"] .tbtn`);
await pg.waitForSelector(`.card[data-id="${ids[0]}"] .tbtn.on`, { timeout: 1000 }); console.log('start1 UI ms', Date.now() - t);
console.log('start2 in-page ms', await pg.evaluate(id => { const t0 = performance.now(); document.querySelector(`.card[data-id="${id}"] .tbtn`).click(); return { ms: Math.round(performance.now() - t0), on: !!document.querySelector(`.card[data-id="${id}"] .tbtn.on`) }; }, ids[1]));
console.log('timerbar runs', await pg.locator('#timerbar .t-run').count());
console.log('hit', await pg.evaluate(id => { const b = document.querySelector(`.card[data-id="${id}"] .tbtn.on`); const r = b.getBoundingClientRect(); const e = document.elementFromPoint(r.x + r.width / 2, r.y + r.height / 2); return e === b || b.contains(e) ? 'button' : (e.id || e.className); }, ids[0]));
// stop job1 immediately while start still pending
t = Date.now(); await pg.click(`.card[data-id="${ids[0]}"] .tbtn.on`); await pg.waitForSelector(`.card[data-id="${ids[0]}"] .tbtn:not(.on)`, { timeout: 1000 }); console.log('stop1 UI ms', Date.now() - t);
await pg.screenshot({ path: new URL('out/timer.png', import.meta.url).pathname });
await pg.waitForTimeout(6000);
const srvLogs = m.call('bootstrap', {}, T0).data.logs;
console.log('server logs', JSON.stringify(srvLogs.map(l => ({ job: l.jobId === ids[0] ? 'A1' : l.jobId === ids[1] ? 'A2' : '?', end: !!l.end }))));
console.log('client running', await pg.evaluate(() => S.logs.filter(l => !l.end).length), 'tmp left', await pg.evaluate(() => S.logs.filter(l => /^tmp_/.test(l.id)).length));
await pg.evaluate(() => T.openEditor()); await pg.waitForTimeout(400); await pg.fill('#e-code', 'NEW-9');
const tn = Date.now(); await pg.click('#sheetFoot [data-act="save"]');
await pg.waitForFunction(() => S.jobs.some(j => j.code === 'NEW-9'), null, { timeout: 1000 }); console.log('new job on board ms', Date.now() - tn, 'pending', await pg.evaluate(() => S.jobs.find(j => j.code === 'NEW-9').pending));
await pg.waitForTimeout(3000); console.log('after save real id', await pg.evaluate(() => { const j = S.jobs.filter(j => j.code === 'NEW-9'); return j.length + ' ' + j[0].id.slice(0, 2) + ' pending:' + !!j[0].pending; }));
console.log('errors', errs.join('|') || 'none');
await b.close(); srv.close();
